apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/jx-dev-org-mikec/test1:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/jx-dev-org-mikec/test1:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: test1
        chartPath: charts/test1
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/jx-dev-org-mikec/test1'
          image.tag: '{{.DIGEST_HEX}}'
